export const clients = [
  { name: "KFC", src: "/clients/kfc.jpeg" },
  { name: "Burger Lab", src: "/clients/burger-lab.png" },
  { name: "Noor Textile", src: "/clients/noor-textile.jpeg" },
  { name: "Sasta.pk", src: "/clients/sasta-pk.jpeg" },
  { name: "Sifona", src: "/clients/sifona.jpeg" },
  { name: "Mothercare", src: "/clients/mothercare.jpeg" },
  { name: "Shop n Drop", src: "/clients/shopndrop.jpeg" },
  { name: "Paklap.pk", src: "/clients/paklap.jpeg" },
  { name: "Fittworth USA", src: "/clients/fittworth.jpeg" },
  { name: "The Vault", src: "/clients/the-vault.jpeg" },
  { name: "Stop & Shop", src: "/clients/stop-and-shop.jpeg" },
  { name: "Oaks", src: "/clients/oaks.jpeg" },
  { name: "Bin Hashim", src: "/clients/bin-hashim.jpeg" },
  { name: "Marcas", src: "/clients/marcas.jpeg" },
  { name: "Oriflame", src: "/clients/oriflame.png" },
  { name: "Gomila", src: "/clients/gomila.png" },
  { name: "Montivo", src: "/clients/montivo.jpeg" },
  { name: "AD Fashion", src: "/clients/adfashion.png" },
  { name: "Ghani's", src: "/clients/ghanis.png" },
  { name: "Highty", src: "/clients/highty.png" },
  { name: "Parcel Go", src: "/clients/parcel-go.png" },
  { name: "Blueberry Organic", src: "/clients/blueberry.png" },
  { name: "Insta", src: "/clients/insta.png" },
  { name: "Herbion", src: "/clients/herbion.png" },
  { name: "Smartlane", src: "/clients/smartlane.png" },
  { name: "The Protein Factory", src: "/clients/protein-factory.png" },
  { name: "DigiKhata", src: "/clients/digikhata.png" },
  { name: "EGO", src: "/clients/ego.png" },
  { name: "Edenrobe", src: "/clients/edenrobe.png" },
] as const;

export const couriers = [
  { name: "TCS", src: "/couriers/tcs.png" },
  { name: "Leopards", src: "/couriers/leopards.png" },
  { name: "M&P", src: "/couriers/mnp.png" },
  { name: "Trax", src: "/couriers/trax.png" },
] as const;
